export const FEATURE_FLAGS = {
  AGENTOS_ENABLE_PROSPECTING_CENTER: process.env.AGENTOS_ENABLE_PROSPECTING_CENTER === "true",
  AGENTOS_ENABLE_PROSPECTING_EMAIL_SEND: process.env.AGENTOS_ENABLE_PROSPECTING_EMAIL_SEND === "true",
  AGENTOS_ENABLE_PROSPECTING_CRAWLER: process.env.AGENTOS_ENABLE_PROSPECTING_CRAWLER === "true",
  AGENTOS_ENABLE_PROSPECTING_AUTOMATION: process.env.AGENTOS_ENABLE_PROSPECTING_AUTOMATION === "true",
};
