FROM node:20-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --include=dev

COPY . .

RUN npm run prisma:generate

ENV NODE_ENV=production

CMD ["npm", "run", "worker:start"]
